from PyQt6.QtGui import QFont, QFontMetrics


MAIN_FONT_SIZE = 10

MAIN_FONT_FAMILY = "Candara"
NUMBER_FONT_FAMILY = "Times New Roman"

NUMBER_FONT = QFont(NUMBER_FONT_FAMILY, MAIN_FONT_SIZE)
NUMBER_BOLD_FONT = QFont(NUMBER_FONT_FAMILY, MAIN_FONT_SIZE)
NUMBER_BOLD_FONT.setBold(True)

MAIN_FONT = QFont(MAIN_FONT_FAMILY, MAIN_FONT_SIZE)
MAIN_BOLD_FONT = QFont(MAIN_FONT_FAMILY, MAIN_FONT_SIZE)
MAIN_BOLD_FONT.setBold(True)

MAIN_FONT_METRICS = QFontMetrics(MAIN_FONT)
MAIN_BOLD_FONT_METRICS = QFontMetrics(MAIN_BOLD_FONT)